In [2]:
# numpy는 숫자 계산을 빠르고 쉽게 도와주는 파이썬 라이브러리입니다.
# 인공지능 코드에서는 배열, 행렬, 수학 함수 계산이 자주 필요하기 때문에 numpy를 많이 사용합니다.

import numpy as np
from math import e

In [3]:
# X는 입력값입니다.
# 여기서는 사람의 키(cm)를 입력값으로 사용합니다.
# 머신러닝에서는 사람이 정리한 표(csv 등)의 각 컬럼 값이 모델의 입력값으로 사용되는 경우가 많습니다.
# np.array()는 여러 개의 숫자를 하나의 배열로 묶어주는 함수입니다.
X = np.array([160, 170, 180, 190])

X

array([160, 170, 180, 190])

In [4]:
# y는 실제 정답값입니다.
# 이 예제에서는 사람이 농구선수인지 아닌지를 0 또는 1로 표시합니다.
# 0: 농구선수가 아님, 1: 농구선수가 맞음
y = np.array([0, 0, 1, 1])

y

array([0, 0, 1, 1])

In [5]:
# a는 가중치(weight)입니다.
# 가중치는 입력값 X가 결과에 얼마나 영향을 주는지를 조절하는 값입니다.
a = 0.1

# b는 편향(bias)입니다.
# 편향은 전체 계산 결과의 기준선을 조정하는 값입니다.
b = -17

In [6]:
# 수식에서는 H(x) = ax + b라고 씁니다.
# 하지만 코드에서는 변수 이름에 괄호를 사용할 수 없으므로 H라고 저장합니다.

# H(x)는 선형 회귀에서 배운 ax + b 형태와 같은 선형 계산 결과입니다.
# 단, 여기서는 회귀 문제처럼 H(x)를 최종 예측값으로 사용하지 않습니다.
# 이진 분류에서는 H(x)를 시그모이드 함수에 넣기 전의 "선형 점수"로 사용합니다.
H = a * X + b

print('선형 계산 결과 H(x):', H)

선형 계산 결과 H(x): [-1.  0.  1.  2.]


In [7]:
# sigmoid() 함수는 H(x)를 0과 1 사이의 값으로 변환하는 함수입니다.
# H(x)는 선형 계산 결과이므로 그대로는 확률로 해석하기 어렵습니다.
# 그래서 시그모이드 함수를 사용해 H(x)를 예측 확률값으로 바꿉니다.
def sigmoid(H):
    return 1 / (1 + e**(-H))

In [8]:
# z는 시그모이드 함수를 통과한 예측 확률값입니다.

# 수식으로 쓰면 다음과 같습니다.
# z = sigmoid(H(x))

# z는 항상 0과 1 사이의 값을 가집니다.
# z가 1에 가까우면 모델은 y=1일 확률이 높다고 예측한 것입니다.
# z가 0에 가까우면 모델은 y=0일 확률이 높다고 예측한 것입니다.
z = sigmoid(H)

print('시그모이드 예측 확률 z:', z)

시그모이드 예측 확률 z: [0.26894142 0.5        0.73105858 0.88079708]


In [9]:
costs = -(y * np.log(z) + (1-y) * np.log(1-z))

costs

array([0.31326169, 0.69314718, 0.31326169, 0.12692801])

In [10]:
np.mean(costs)

np.float64(0.36164964165984087)

In [11]:
# Binary Cross Entropy (BCE)는 이진 분류에서 자주 사용하는 비용 함수입니다.
# BCE는 예측 확률값 z와 실제 정답 y의 차이를 비용(Cost)으로 계산합니다.

# BCE 공식:
# C(z, y) = -y * log(z) - (1 - y) * log(1 - z)

# y가 1이면 첫 번째 항 -y * log(z)가 작동합니다.
# 이때 z가 1에 가까울수록 -log(z)는 0에 가까워져 비용이 작아집니다.
costs = -(y * np.log(z) + (1-y) * np.log(1-z))

print('각 샘플의 비용(Cost):', costs)

각 샘플의 비용(Cost): [0.31326169 0.69314718 0.31326169 0.12692801]


In [12]:
# 평균 비용을 계산합니다.
# costs에는 각 샘플별 비용이 들어 있습니다.
# 모델 전체의 성능을 하나의 숫자로 보고 싶다면 각 샘플의 비용을 평균냅니다.
mean_cost = np.mean(costs)

# 이 교재에서는 Cost라는 용어로 통일합니다.
print('평균 비용(Cost):', mean_cost)

평균 비용(Cost): 0.36164964165984087
